### PR TITLE
fix: correct message in comment publishing command

### PR DESCRIPTION
**Pull request by xTCry**

### CODE REVIEW

**Comment by chr233** [comment]
I have no idea about this change's sense 🤔

**Comment by xTCry** [comment]
You should check it out for yourself.
If you publish a review using the command and specify not one word, but several, then they will all be without spaces, but with commas.

If I use like this `PREC ASF 440 Cool game`, then I will get this as output `Cool,game`
However, it is implied to receive such a comment `Cool game`

**Comment by woctezuma** [comment]
I don't know about this code, but shouldn't it be as follows to solve your issue?

```diff
- Utilities.GetArgsAsText(args, 3, ","))
+ Utilities.GetArgsAsText(args, 3, " "))
```

**Comment by xTCry** [comment]
I'm not completely familiar with these functions either, but I tested them in the sandbox and they work, in this case, similarly.

Your first option is similar to the second, so there shouldn't be any difference.
Usually the first your option is used just to combine the passed arguments with a comma (or something else).

The main thing is to correct the typo. You can, as in your version, simply replace `","` with `" "`

**Comment by woctezuma** [comment]
Okay, and I see `message` is a correct variable.

https://github.com/chr233/ASFEnhance/blob/35e05cb5971fb8eaa2360e76a0d486a25e25e8ae/ASFEnhance/ASFEnhance.cs#L421

**Comment by xTCry** [comment]
@chr233 , please look at comments, we have sorted everything out here.
> I have no idea about this change's sense 🤔

This PR corrects the publication of the review with the correct formation of the message (separates the words with spaces, not commas)

**Comment by chr233** [comment]
so what do u fix, can you show the examples

**Comment by xTCry** [comment]
Ufhh... 

 As stated here, you just need to correct the typo "," to " ".

https://github.com/chr233/ASFEnhance/pull/40#issuecomment-1326781490

 Or use my PR to solve the problem.
 The essence here is the same - to join the words with spaces, not commas.

**Pull request merged**
