### PR TITLE
Fix even vote command. closes #167

### LINKED ISSUE #167: !VOTE only works for the first bot
I have tried to vote for the 11 nominations:
```bash
!vote ASF 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2225070
```
I can [see](https://store.steampowered.com/steamawards/nominations/76561198028705366?k=2206531303751302320) that the appIDs are correctly understood for the first bot. **However, the command only works for the first bot!**

```
>> !vote ASF 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2225070

<MainBot> Nominate at least 1 game: √
Nominate a game in each category: √
Play a game you nominated: √
Review or update your review of a game you nominated: √
```

```
>> !checkvote ASF

<MainBot> Nominate at least 1 game: √
Nominate a game in each category: √
Play a game you nominated: √
Review or update your review of a game you nominated: √

<AltBot1> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×

<AltBot2> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×

<AltBot3> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
```

### PR DESCRIPTION
**Pull request by Rudokhvist**
Thank you for considering the inclusion of this merge request :P

### CODE REVIEW

**Comment by woctezuma** [comment]
Fix #167 a priori.

**Comment by Rudokhvist** [comment]
You fixed only part of issue - incorrect [Bots] parameter parsing. But 2.0.1.1 still only can do 10 out of 11 tasks, that still needs fix. If you want I can remove parts that already fixed from this PR, when I was preparing it - 2.0.1.1 wasn't yet a thing, and by coincidence we did the same fix at the same time.

**Comment by woctezuma** [comment]
Fix:
- #168

**Comment by chr233** [comment]
sorry dude, didn't see this before i fixed myself

**Pull request merged**
